### PR TITLE
Add Molex 73251-1150 SMA connector

### PR DESCRIPTION
**Pull request by RX14**
Tested on a recent board

### CODE REVIEW

**Comment by RX14** [comment]
Bot!

**Comment by RX14** [comment]
The only question I have about this part is the vias being included in the package. They're in the recommended footprint, but it might be worth at least having a variant without them?

**Comment by carrotIndustries** [comment]
> They're in the recommended footprint, but it might be worth at least having a variant without them?

I think so, so users can add vias as they see fit. Also, vias baked into the package might be in the way of what's on the board.

**Comment by RX14** [comment]
Bot!

I've added a variant without vias. It's the default right now, but it could be switched.

**Pull request merged**
