### PR TITLE
Added SOD-323 package and 1N4148WS

### PR DESCRIPTION
**Pull request by atoav**
Footprint in accordance to [figure 2 in this pdf](https://www.nxp.com/docs/en/package-information/SOD323.pdf)

### CODE REVIEW

**Comment by atoav** [comment]
3D models are again mine

**Comment by carrotIndustries** [comment]
I don't really like the silkscreen on that one since it's obscured by the part body. See the SMA diode for the appropriate silkscreen.

**Comment by atoav** [comment]
Like this?  
2018-06-08 13_50_19-horizon pool manager

**Comment by atoav** [comment]
If the silkscreen is okay, this could be finished

**Pull request merged**
