### PR TITLE
Add XR21V1410 USB UART

### PR DESCRIPTION
**Pull request by RX14**
Nice cheap widely available USB UART chip using CDC device class. Tested on a board and works great!

### CODE REVIEW

**Comment by carrotIndustries** [comment]
Bot!

**Comment by jue89** [comment]
I'd put RX and TX on the right side of the symbol. They are strongly coupled to the GPIOs, since they can be used as handshake signals. Furthermore, my inner mock is slightly triggered that the GND pin got its own *row* and the VCC pin shares half of its *row* with the RX pin ;)

**Comment by RX14** [comment]
Yeah, I think those are good points. The symbol is a bit messy, it should probably be expanded a fair bit more.

**Comment by RX14** [comment]
Bot!

Much happier with this version

**Comment by carrotIndustries** [comment]
LGTM, though description could use a bit less ALLCAPS. Maybe flag words with more than 5 letters and all of them being uppercase as a warning?

**Comment by RX14** [comment]
I must have been tired when I made that part - I don't usually copy directly from the datasheet!

**Comment by RX14** [comment]
Done! The diff is simple enough it's not worth calling the bot.

**Pull request merged**
