### PR TITLE
Add Keystone 4628 Fuse Holder

### PR DESCRIPTION
**Pull request by jue89**
- symbol/unit/entity: fuse symbol based on the resistor symbol
- part/package: Keystone 4628

### CODE REVIEW

**Comment by jue89** [comment]
Bot!

**Comment by carrotIndustries** [comment]
LGTM, assy refdes could be a bit larger though

**Comment by jue89** [comment]
Bot!

**Comment by carrotIndustries** [comment]
Oh, just one more thing, the silkscreen should roughly indicate the package outline.

**Comment by jue89** [comment]
Bot!

**Comment by carrotIndustries** [comment]
Bot! again to check versions

**Comment by jue89** [comment]
Thank you for your fast review! :)

**Pull request merged**
