### PR TITLE
Add testpoint symbol and basic package

### PR DESCRIPTION
**Pull request by RX14**
Just a basic circular 1mm test point for manual probing

### CODE REVIEW

**Comment by carrotIndustries** [comment]
Bot!

**Comment by carrotIndustries** [comment]
Bot! again. Triggering the bot in fast succession doesn't work that well...

**Comment by carrotIndustries** [comment]
Text for some orientations is overlapping symbol graphics.

**Comment by RX14** [comment]
I have no idea where to put the value which would prevent that from happening. What is the group tag used for anyway?

**Comment by RX14** [comment]
Updated placements

Bot!

**Comment by RX14** [comment]
Bot!

**Comment by carrotIndustries** [comment]
> I've never had it appear

Multiline value text is used in https://horizon-eda.readthedocs.io/en/latest/copy-layout-placement.html and https://blog.horizon-eda.org/progress/2021/03/06/progress-2021-02.html#parametric-data-in-schematic

**Pull request merged**
