### PR TITLE
Add 4ch ESD protection symbol and TI ESDS3x4 TVS diodes

### PR DESCRIPTION
**Pull request by RX14**
Tested in a recent project

### CODE REVIEW

**Comment by carrotIndustries** [comment]
Bot!

**Comment by carrotIndustries** [comment]
You could add dots at the junctions where three or more lines meet. LGTM otherwise.

**Comment by RX14** [comment]
Done!

**Comment by RX14** [comment]
Bot!

**Comment by RX14** [comment]
Those dots dont seem to render like they do in horizon

**Pull request merged**
