### PR TITLE
Add KH-TYPE-C-16P Type-C Connector

### PR DESCRIPTION
**Pull request by RX14**
tested this part on a board, footprint is good.

### CODE REVIEW

**Comment by RX14** [comment]
Bot!

**Comment by RX14** [comment]
Bot!

**Comment by RX14** [comment]
Assembly layer refdes now fits in the outline.

**Comment by carrotIndustries** [comment]
No datasheet?

**Comment by RX14** [comment]
Bot!

**Comment by tkornack** [comment]
Sometimes I see the mounting holes labeled using M1...Mx. Does S1-S4 specifically mean shield?

**Pull request merged**
