### PR TITLE
Add RT9193 LDO regulator

### PR DESCRIPTION
**Pull request by fk0815**

### CODE REVIEW

**Comment by fk0815** [comment]
Bot!

**Comment by fk0815** [comment]
Bot!

**Comment by RX14** [comment]
The entity here might be worth renaming to be generic like the other LDO entity/unit/symbols. Also needs regulator tag and I'd remove the orientation-dependent texts.

**Comment by fk0815** [comment]
Bot!

**Comment by fk0815** [comment]
> The entity here might be worth renaming to be generic like the other LDO entity/unit/symbols.

The BP pin is somehow special for that regulator. It allows to bypass the internal voltage reference by a capacitor, which allows to operate the regulator as a very low noise device. Not sure if that should be kept as a generic entity/unit/symbol.

**Comment by RX14** [comment]
There should probably be a `RT9193-GB`, which is inherited to `RT9193-33GB` as a 3.3V specific part. That means the other voltages can be added in the future easily.

**Comment by fk0815** [comment]
Bot!

**Comment by carrotIndustries** [comment]
For consistency reasons, it'd be good if the symbol had the same size as the "Buck converter with enable" one.

**Comment by fk0815** [comment]
Bot!

**Pull request merged**
