### PR TITLE
Add AZ1117{CD,IH} versions and DPAK TO-252-3 package

### PR DESCRIPTION
**Pull request by RX14**
Common regulators to use, in 2 packages.

### CODE REVIEW

**Comment by RX14** [comment]
Bot!

**Comment by RX14** [comment]
Whoops, I forgot to use a seperate entity for the adjustable regulators

**Comment by RX14** [comment]
Bot!

**Comment by RX14** [comment]
The "use polygons to draw outlines" warning for DPAK is also bogus: the outline of the package is drawn with a polygon, with the added inner details to create the illusion of legs and tab are done using lines.

**Comment by carrotIndustries** [comment]
The proper way to do pads with patterned solder paste is to create a package-specific pad.

**Comment by RX14** [comment]
It is a package-specific pad?

**Comment by RX14** [comment]
Bot!

Fixed.

**Comment by RX14** [comment]
Bot!

Whoops, forgot to add the padstack.

**Comment by RX14** [comment]
Ping again: I think this is ready to merge.

**Pull request merged**
