### PR TITLE
Add Horizon logo silkscreen decal

### PR DESCRIPTION
**Pull request by unrelentingtech**
Converted from SVG via Inkscape's DXF export. Probably should've downscaled in Inkscape first, the circles ended up *quite* detailed… although the renderer can handle it just fine :)

### CODE REVIEW

**Comment by unrelentingtech** [comment]
Bot!

**Comment by carrotIndustries** [comment]
Bot! again

**Comment by carrotIndustries** [comment]
You could significantly reduce the vertex count by using arcs, the outside circle could be done by a line circle.

**Comment by unrelentingtech** [comment]
Oh right, that works nicely. Did both using line circles actually.

Bot!

**Comment by unrelentingtech** [comment]
Bot!

// Oh right, that works nicely. Did both using line circles actually.

**Pull request merged**
