### PR TITLE
Add ICM7555 timer IC

### PR DESCRIPTION
**Pull request by jue89**
* part

### CODE REVIEW

**Comment by jue89** [comment]
Bot!

**Comment by RX14** [comment]
This should probably have been part of #225. No problem for this PR but the next one like it could combine both

**Comment by jue89** [comment]
I thought both PRs can be merged and reviewed individually. So I split it into two PRs ;)

**Comment by carrotIndustries** [comment]
Orderable MPNs should include all MPNs, so ICM7555CBAZ and ICM7555CBAZ-T.

**Comment by jue89** [comment]
Bot!

**Pull request merged**
