### PR TITLE
Molex 1054500101 USB Type-C Receptable

### PR DESCRIPTION
**Pull request by skuhlabs**
Molex Type-C Receptable (1054500101), Manufacturer Page: https://www.molex.com/molex/products/part-detail/io_connectors/1054500101, Datasheet: https://www.molex.com/pdm_docs/sd/1054500101_sd.pdf.

### CODE REVIEW

**Comment by starlord-a** [comment]
Bot!

**Comment by carrotIndustries** [comment]
Pins in symbol are place incorrectly

**Comment by starlord-a** [comment]
> Pins in symbol are place incorrectly

Not sure what you mean.

**Comment by carrotIndustries** [comment]
> Not sure what you mean.

The pin's connection points are on the box, the end of the pin's line should be.

**Comment by starlord-a** [comment]
> > Not sure what you mean.
> 
> The pin's connection points are on the box, the end of the pin's line should be.

Ah, gotcha - correcting - thanks!

**Comment by starlord-a** [comment]
Correcting symbol pin placement.

**Comment by RX14** [comment]
Where's the model in this PR from?

**Pull request closed without merging**
