### PR TITLE
Ap62XXXWU step down converters

### PR DESCRIPTION
**Pull request by LHSmicius**
All AP62XXXWU voltage converters added.
Also TSOP-26 package added.
image

### CODE REVIEW

**Comment by LHSmicius** [comment]
Bot!
I didn't add .step file for 3D view, but I would like to make it, just point me how to do it, please.

**Comment by LHSmicius** [comment]
Bot!

**Comment by LHSmicius** [comment]
Bot!

**Comment by LHSmicius** [comment]
Bot!

**Comment by RX14** [comment]
I think sot-23-6 is identical to (t)sot-26. I think these parts should use sot-23-6 package but perhaps sot-23-6 should be renamed to include a reference to sot-26. Everything else looks great!

**Comment by LHSmicius** [comment]
SOT-23-6 just a little bit wider (0.2 mm). Crazy :DD
SOT-23-6:
image
TSOT-26:
image

**Comment by RX14** [comment]
I think that difference is as much down to manufacturer variance than anything else, and in practice the same footprint will always work for both.

**Comment by LHSmicius** [comment]
Bot!

**Comment by LHSmicius** [comment]
Bot!

**Pull request merged**
