### PR TITLE
Add Digital Isolator Si8422xB

### PR DESCRIPTION
**Pull request by jue89**
* symbol
* part

### CODE REVIEW

**Comment by carrotIndustries** [comment]
Bot!

**Comment by carrotIndustries** [comment]
LGTM, what's up with the SOT-23-6 being deleted?

**Comment by jue89** [comment]
Whoops. IDK how that sneaked in ... I'll fixed that soon.

Are you okay with push-force?
Or should I work with fixups and you'll squash them during merge process?

**Comment by carrotIndustries** [comment]
Force push is okay.

**Comment by jue89** [comment]
And SOT-23-6 ist back :)

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Bot!

**Comment by RX14** [comment]
I don't think that orderable MPNs should be used to differentiate between speed grades, they are functionally different. Everything else looks good, especially the nice symbol.

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
> I don't think that orderable MPNs should be used to differentiate between speed grades, they are functionally different. Everything else looks good, especially the nice symbol.

Thanks for reviewing! I split it into two different parts.

**Pull request merged**
