### PR TITLE
Added MCP1640 device

### PR DESCRIPTION
**Pull request by fk0815**
Signed-off-by: Frank Kunz <mailinglists@kunz-im-inter.net>

### CODE REVIEW

**Comment by fk0815** [comment]
Bot!

**Comment by fk0815** [comment]
There is just a warning about the symbol, but no details what is the problem.

**Comment by fk0815** [comment]
Bot!

**Comment by RX14** [comment]
My only suggestion is to add the "regulator" tag as well as the others

**Comment by carrotIndustries** [comment]
- no need for orientation-dependent text placements
 - pins on top/bottom should use perpendicular text
 - en and vfb pins should be at the the same height

**Comment by RX14** [comment]
It feels like the whole symbol could be a bit less tall as well

**Comment by fk0815** [comment]
Bot!

**Pull request merged**
