### PR TITLE
add 93LC46B EEPROM

### PR DESCRIPTION
**Pull request by jue89**
* part
* symbol

### CODE REVIEW

**Comment by jue89** [comment]
Bot!

**Comment by carrotIndustries** [comment]
As far as I can tell, this device is part of a greater family, so it probably makes sense to introduce a base part and inherit from that one.

**Comment by RX14** [comment]
The symbol perhaps looks even more generic than just one manufacturer or logic family as well. Though, that could easily be renamed later

**Comment by jue89** [comment]
If the symbol should become a common serial flash I would rename the pins: VCC and VSS are the names from the datasheet. I would expect the combination VDD/VSS or VCC/VEE ... in a common symbol I'd select VCC/GND.

**Comment by jue89** [comment]
Symbol ist generic. I generated a base part for 1kBit EEPROMs.

I added a base part for the EEPROMs with larger memory in the first place - but that was a little bit dumb - the datasheet is wrong for parts with more memory ... or is this the right solution?

- Basepart 93xxx6AB/SN (pin mapping, entity)
   - Basepart 93xx46AB/SN (datasheet link)
      - Part 93LC46B/SN

**Comment by jue89** [comment]
Bot!

**Comment by RX14** [comment]
LGTM

**Comment by carrotIndustries** [comment]
@RX14 How about renaming the `CS` pin to `~CS` as it's low active?

**Comment by RX14** [comment]
<abbr title="Looks Even Better To Me Now">LEBTMN</abbr>

**Pull request merged**
