### PR TITLE
Add ideal diode MAX40200

### PR DESCRIPTION
**Pull request by jue89**
- symbol/unit/entity for ideal diodes with enable pin
- part MAX40200AUK+

### CODE REVIEW

**Comment by jue89** [comment]
Bot!

**Comment by carrotIndustries** [comment]
Wouldn't it make more sense to put the input left and output right?

**Comment by jue89** [comment]
> Wouldn't it make more sense to put the input left and output right?

Yes, I fully agree. I was biased by the schematic I needed the symbol for :D I'll mirror the symbol.

**Comment by jue89** [comment]
Bot!

**Comment by RX14** [comment]
For this part, it might be ideal to support every orientation, or at least left/right, by fixing the text locations to make that look nice.

**Comment by jue89** [comment]
Bot!

**Comment by RX14** [comment]
The rest are a bit funky, but normal and mirrored are fine so this looks OK to me

**Comment by jue89** [comment]
> I wouldn't complain if the 180degree ones were improved though.

Yeah - but in that case the GND ping is in the top section of the symbol. That's something that shouldn't be done in my opinion - no one expects GND to be on top when reading schematics ;)

**Comment by RX14** [comment]
ah, you're right

it might be neat to have more orientation-dependent symbols but thats for another day

**Pull request merged**
