### PR TITLE
add MOC3063SM

### PR DESCRIPTION
**Pull request by jue89**
This PR adds the ON Semiconductor Opto-Triac MOC3063SM.

### CODE REVIEW

**Comment by jue89** [comment]
Bot!

**Comment by carrotIndustries** [comment]
please rebase you pr onto latest master where I (hopefully) fixed the bot

**Comment by carrotIndustries** [comment]
Bot!

**Comment by jue89** [comment]
I've rebased on master manually.

The "Update PR" button didn't do that. But I guess this is by intention.

**Comment by carrotIndustries** [comment]
> The "Update PR" button didn't do that. But I guess this is by intention.

Yes. Normally, rebasing PRs isn't necessary. This time it was to get the update workflow.

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
I added the missing tags for the entitiy just using Horizon EDA. Works like a charm! Great feature :)

**Pull request merged**
