### PR TITLE
Add Single Buffer SN74AHCT1G125 for Level Shifting

### PR DESCRIPTION
**Pull request by jue89**
This PR adds a generic unit, symbol, entity and the vendor specific part.

### CODE REVIEW

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Bot!

**Comment by RX14** [comment]
Back [a while ago](https://github.com/horizon-eda/horizon-pool/pull/214#issuecomment-818284617) we decided that inverted pin decorations should only be used on logic gates, not ICs. Since the inverted decoration is on the box, not the gate here, I think it should be `~OE` instead.

**Comment by jue89** [comment]
> Back [a while ago](https://github.com/horizon-eda/horizon-pool/pull/214#issuecomment-818284617) we decided that inverted pin decorations should only be used on logic gates, not ICs. Since the inverted decoration is on the box, not the gate here, I think it should be `~OE` instead.

Oh I haven't noticed that. But I recall a discussion about that in the past :D Sorry, I didn't remember it.

I'll fix it tonight. Thank you for looking into this PR :)

**Comment by jue89** [comment]
Bot!

**Pull request merged**
