### PR TITLE
Add modular jack TE Connectivity 5555980-1

### PR DESCRIPTION
**Pull request by jue89**
Modular jack TE Connectivity 5555980-1:

* package
* part

### CODE REVIEW

**Comment by carrotIndustries** [comment]
Bot!

**Comment by jue89** [comment]
Thanks for review getting started :)
Please wait for a little update of the footprint - I've produced a PCB and the mechanical holes are a little bit too tight.

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Bot!

**Comment by carrotIndustries** [comment]
Does the 3D model's license allow for redistribution?

**Comment by jue89** [comment]
I've created the model by myself. So we don't have any restrictions regarding its redistribution :)

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
@carrotIndustries are there any concerns hindering the merge of this modular jack?

**Comment by jue89** [comment]
Thank you!

**Pull request merged**
