### PR TITLE
add FT4232H Quad USB UART interface

### PR DESCRIPTION
**Pull request by jue89**
* symbol
* part

### CODE REVIEW

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Bot!

**Comment by carrotIndustries** [comment]
- Reset doesn't indicate low-activeness (either add dot name the pin accordingly)
 - Some more tags can be useful, how about `uart` and `usb`?

**Comment by jue89** [comment]
Good point!

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
A board has been produced using this part. Works flawlessly.

**Pull request merged**
