### PR TITLE
USBLC6-4SC6, Very Low Capacitance ESD Protection

### PR DESCRIPTION
**Pull request by skuhlabs**
ESD protection for high-speed interfaces, such as USB 2.0, Ethernet links and video lines.

### CODE REVIEW

**Comment by carrotIndustries** [comment]
Bot!

**Comment by starlord-a** [comment]
Will also correct the REFDES and VALUE soon...ish...

**Comment by starlord-a** [comment]
Updated the symbol to match convetions.

**Comment by starlord-a** [comment]
Updating symbol, compacting it - learning new tricks with the symbol editor so I am optimizing the symbols little by little. This should be the last update for this part.

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Thank you for your contribution. I've brought the sister / brother of this ESD protection into the pool: https://github.com/horizon-eda/horizon-pool/pull/165

Some comments on your part - I haven't checked everything, yet:
- Try to be as generic as possible. The unit, entity and symbol can be used by other ESD protection parts. I'd recommend to rename them to "4CH ESD Protection" and remove the manufacturer.
- I think you can use the already-existing package SOT-23-6.
- I'd love to see your symbol to be aligned with the existing one. Just duplicate the existing symbol and modify it accordingly.

**Pull request closed without merging**
