### PR TITLE
Add misc devices

### PR DESCRIPTION
**Pull request by fk0815**
Includes:
- MCP1640 boost converter
- RFM9x LoRa modem
- RT9193 LDO regulator
- ATmega16/32 MCU

### CODE REVIEW

**Comment by carrotIndustries** [comment]
Bot!

**Comment by fk0815** [comment]
Bot!

**Comment by fk0815** [comment]
Bot!

**Comment by fk0815** [comment]
Bot!

**Comment by fk0815** [comment]
Bot!

**Comment by fk0815** [comment]
Bot!

**Comment by jue89** [comment]
Would you mind to split this PR into one PR per part (should be 4, I guess)? It would make its review easier.

**Comment by fk0815** [comment]
Closed by splitting into dedicated PRs:
https://github.com/horizon-eda/horizon-pool/pull/212
https://github.com/horizon-eda/horizon-pool/pull/213
https://github.com/horizon-eda/horizon-pool/pull/214
https://github.com/horizon-eda/horizon-pool/pull/215

**Pull request closed without merging**
