### PR TITLE
Add ADR44x Voltage
References

### PR DESCRIPTION
**Pull request by fk0815**
New Part with symbol, unit and entity
Ultralow Noise, LDO XFET Voltage References with Current Sink and Source

### CODE REVIEW

**Comment by fk0815** [comment]
Bot!

**Comment by carrotIndustries** [comment]
- GND pin text should be perpendicular
- The parts listed in the orderable MPNs are different parts, these should be derived parts. Only use oderable MPNs for different packaging variants (e.g. tube vs tray).

**Comment by fk0815** [comment]
Bot!

**Comment by fk0815** [comment]
Bot!

**Pull request merged**
