### PR TITLE
Added Dual Diode (series), SOT-23 package and BAV199

### PR DESCRIPTION
**Pull request by atoav**
Added symbol, unit and entity for Dual Diodes (series) the SOT-23 package and BAV199 part. The package and the part are based on [this datasheet](https://www.infineon.com/dgdl/Infineon-BAV199SERIES-DS-v01_01-en.pdf?fileId=db3a30431400ef6801141cba733104e5)

### CODE REVIEW

**Comment by carrotIndustries** [comment]
- use ipc zero orientations (pin 1 on upper left corner)
 - to keep things consistent, base the sot-23 package on the already existing sot-23-5 package by deleting the superfluous pins

**Comment by atoav** [comment]
The 3D-model comes from the kicad library

**Comment by carrotIndustries** [comment]
- Courtyard and package outline look wrong
- 3D model is missing in package

**Comment by carrotIndustries** [comment]
- swap groups for pins are incorrect on series diode
 - use shorter pin names on series diode (see common cathode one)
 - support text placements for common cathode diode as well

**Comment by atoav** [comment]
Okay I think this one is fine now

**Comment by carrotIndustries** [comment]
- Why do series and common cathode diode have different symbols in terms of pin placement?
- Symbol text placement needs rework to accommodate multi line value

**Comment by atoav** [comment]
Bot!

**Comment by atoav** [comment]
Not sure what the symbol warnings are about (they don't show up in the details) but I guess this is ready to be merged

**Comment by RX14** [comment]
- For BAV170VL, the VL part is part of the ordering code not the product code and should go in orderable MPNs
- BAV199 could optionally have ordering codes added
- `$REFDES` and `$VALUE` on passive symbols typically have one less grid division of space between them
- SOT-23 pads should probably be roundrect

**Comment by RX14** [comment]
(also thanks for making me realise that i've numbered the SOT-23 pads wrong in the package in my pool, and all the boards i've laying on my desk to assemble are fuckered)

**Comment by atoav** [comment]
> (also thanks for making me realise that i've numbered the SOT-23 pads wrong in the package in my pool, and all the boards i've laying on my desk to assemble are fuckered)

Oh damn, my condolences. Good suggestions otherwise, will incorporate them soon

**Comment by atoav** [comment]
@RX14 Didn't find orderable MPNs for Infineon BAV199 (other than "BAV199") on their website/in the datasheet. If I overlooked something here, feel free to post and I will add it.

**Comment by RX14** [comment]
Bot!

**Comment by RX14** [comment]
The standard for corner radius is `min(0.25mm, shortest_side/4)` rounded to 0.01mm. Otherwise, perfect!

**Comment by atoav** [comment]
> The standard for corner radius is min(0.25mm, shortest_side/4) rounded to 0.01mm. Otherwise, perfect!

A curious didn't know that. However mostly non of the packages currently in the pool use rounded pads, so there would be a lot of work to do ; )

**Comment by RX14** [comment]
> However mostly non of the packages currently in the pool use rounded pads

the R and C SMT passives do, and all new packages I'm adding do. It'll take a while but I hope to improve this in the future.

LGTM.

**Review by RX14 — APPROVED** [review]

**Comment by atoav** [comment]
> the R and C SMT passives do, and all new packages I'm adding do. It'll take a while but I hope to improve this in the future.

Do you think there would be a benefit to add multiple alternative footprints (maybe rounded, unrounded, handsoldering, ...), or just rounded?

**Comment by RX14** [comment]
> Do you think there would be a benefit to add multiple alternative footprints (maybe rounded, unrounded, handsoldering, ...), or just rounded?

I don't think so for rounded/unrounded. handsolder/stencil, yes.

**Comment by carrotIndustries** [comment]
One of the pins in the Common cathode symbol looks to be slightly too long a it protrudes into the diode triangle.

**Comment by atoav** [comment]
Bot!

**Comment by atoav** [comment]
Now that this is fixed, I guess it is really ready to merge. I am replacing the SOT-23 package on my other PRs with this one:
- #73 
- #78 
- #126 
- #150
- #234 

There is one other PR from @fruchti who might want to update to this package as well: #133

**Comment by carrotIndustries** [comment]
Bot!

**Comment by atoav** [comment]
> Bot!

10 hours ago... huh did the bot not fire or am I mistaken? Usually it adds the small rocket icon to the post in question right?

**Comment by carrotIndustries** [comment]
Bot!

Github actions was "experiencing degraded availability", i.e. broken: https://www.githubstatus.com/incidents/lc8s9rtyjmgq

**Comment by atoav** [comment]
Except for the symbol warnings, which are a bit weird this lgtm

**Comment by carrotIndustries** [comment]
Sorry, just noticed one last thing:

> packages/ic/smd/sot/sot-23-alternate-silkscreen/package.json.imp_meta
> packages/ic/smd/sot/sot-23/package.json.imp_meta

They shouldn't be in the repo and are ignored as per the gitignore rules.

**Comment by atoav** [comment]
I removed them, for some weird reason they have not been in the .gitignore of this branch. Maybe because I created it before .imp_meta was a thing?

**Pull request merged**
