### PR TITLE
Fix all mosfets in lib

### PR DESCRIPTION
**Pull request by LHSmicius**
A lot of work....

### CODE REVIEW

**Comment by LHSmicius** [comment]
Bot!

**Comment by RX14** [comment]
Could you give an overview of the changes made in this PR so that this can be reviewed more easily?

**Comment by LHSmicius** [comment]
I'm glad you asked :)
1. Made symbol "N-channel MOSFET with diode". Also unit and entity for it.
image
It better describes mosfets IMO and this diode is often integrated (long time I didn't see mosfet without flyback diode, actually).
Some mosfets have these gate over voltage protection diode, but I decided to not draw them (they doesn't effect schematic if voltage is in range).
image

2. Made base parts of N and P type mosfets with different packages:
- base N-MOSFET wDiode SOT-523 GSD
- base P-MOSFET wDiode SOT-23 GSD
- base P-MOSFET wDiode SOT-523 GSD
GSD means pin order Gate Source Drain.
Actually I was thinking if these BASE parts helps much, because derived parts inherits only Pin map, tags and package, but for low pin count packages it makes sense, because these packages are very popular.

3. Remake some mosfets (in order to change entity to version with diode).

4. Change part's MPN namings where orderable MPNs were combined with MPN. Also base mosfets renamed for better ordering (when ordering by MPN).

5. Change descriptions to standardize them. V, A, Ω.

6. Add missing tags.

**Comment by RX14** [comment]
I'm concerned that with the new MOSFET entity a lot of existing schematics will break. If all the existing MOSFETS have diodes, then perhaps the existing entity should be renamed so that it has the same ID and existing schematics continue to work. This way there is no unit/symbol around with no (non-base) parts. The non-diode symbol can be kept as an alternative to the one with the diode.

**Comment by LHSmicius** [comment]
Good point. So I will make another PR from master, because this one is too messed up. I'm planning to edit existing symbols "N-channel MOSFET" and "P-channel MOSFET" so that this version will have diode (by default all mosfets do). Only I will have to change entity for last PR dc29ff1c3d032184e4ebc22b31f87c5c9c82e1a2 , most likely it was not used in any schematic (week ago it was merged)

**Comment by LHSmicius** [comment]
This PR can be closed, because PR https://github.com/horizon-eda/horizon-pool/pull/318 is a better version of these changes.

**Pull request closed without merging**
