### PR TITLE
Add JST XH B5B 5 pin header

### PR DESCRIPTION
**Pull request by frmdstryr**
3d model is from kicad

### CODE REVIEW

**Comment by frmdstryr** [comment]
Bot!

**Comment by RX14** [comment]
Perhaps put a little arrow near pin1 like the 2.54mm parts' silkscreen. Otherwise looks great to me.

**Comment by frmdstryr** [comment]
Update silkscreen

**Comment by frmdstryr** [comment]
Also add 8 and 10 pin ones.

**Comment by frmdstryr** [comment]
Bot!

**Comment by frmdstryr** [comment]
Thanks!

**Pull request merged**
