### PR TITLE
Add ADuM1300 Digital Isolator

### PR DESCRIPTION
**Pull request by fk0815**
Add part with symbol, entity and unit, icluding SOIC-16W package with 3D model
Triple-Channel Digital Isolators

### CODE REVIEW

**Comment by fk0815** [comment]
Bot!

**Comment by carrotIndustries** [comment]
These should be different parts, only ADuM1300ARW and ADuM1300ARW-RL should be listed as orderable MPNs as these are the same part, just different packaging options,

**Comment by fk0815** [comment]
Bot!

**Comment by fk0815** [comment]
Bot!

**Comment by carrotIndustries** [comment]
I'd prefer there being a specific base part rather than using a random variant.

**Comment by fk0815** [comment]
Not sure if I understand correct, but do you mean to change this:

image

in a way so that there is a ADuM1300 part and the ADuM1300[ABC]RWZ should be derived parts from that?
In such a case the ADuM1300 part would be not orderable, can you name an example for that?

**Comment by fk0815** [comment]
Bot!

**Comment by carrotIndustries** [comment]
>  In such a case the ADuM1300 part would be not orderable, can you name an example for that?

Yes, that's how it's supposed to be, see the STM32F103RxTx for an example. It's recommended to set the 'base part' flag for parts like these.

**Pull request merged**
