### PR TITLE
Add Darlington array family ULN200xD

### PR DESCRIPTION
**Pull request by jue89**
* symbol, unit, entity: 7ch Darlington array with free wheeling diodes
* part: ULN200[1234]D1013TR by ST

### CODE REVIEW

**Comment by jue89** [comment]
Bot!

**Comment by RX14** [comment]
I think the pads in the package should all be 1.27mm part, not some 1.25 and some 1.3.

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Well I redid the package using the Footprint Generator ... and it happend again :D
Maybe @carrotIndustries has an idea, what's going wrong? It looks like small rounding errors.

**Comment by jue89** [comment]
I corrected the pitch by hand. Looking at the diff clearly shows that the generator quantizes in 0.05mm steps.

**Comment by jue89** [comment]
Bot!

**Comment by carrotIndustries** [comment]
> Looking at the diff clearly shows that the generator quantizes in 0.05mm steps.

If you're using the IPC generator, that's a setting:

image

**Comment by jue89** [comment]
Oh thank you for the info! I always thought, this "Round-off" setting is related to the "Rounded rectangular". What is the purpose of this setting? Why is its default set to `0.05 mm`?

**Comment by RX14** [comment]
looks good to me now

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Enlarged junction diameter to 0.35mm to be aligned with #217.

**Comment by carrotIndustries** [comment]
You could set the symbol pin driver to "open collector" so that the open-collectorness is visible from the symbol.

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
I created the OC symbol by my-self. Otherwise it would have interrupted to net line.
Or do you prefer the original sign with the not-so-pretty interrupted net line?

**Pull request merged**
