### PR TITLE
Add Molex 105400101 USB Type-C connector

### PR DESCRIPTION
**Pull request by RX14**
Tested this on a board of my own, works great.

Closes #185.

### CODE REVIEW

**Comment by carrotIndustries** [comment]
Bot!

**Comment by RX14** [comment]
The "top copper near top silkscreen" clearance here seems to be a bug in horizon to me. Or at least, the arrow pointing to where the intersection is seems erroneous

**Comment by carrotIndustries** [comment]
How about setting vbus, gnd and shield pins to perpendicular?

**Comment by RX14** [comment]
Bot!

**Comment by jue89** [comment]
Duplicate / alternative of #185

**Comment by RX14** [comment]
Ah, might be worth taking the model from there.

**Comment by RX14** [comment]
I'm happy to take the model from #185 if others agree. The model doesn't *look* to be from molex's website so can probably be included.

**Comment by RX14** [comment]
Also: Molex has changed their part naming to exclude the dash, but most stocking distributors still have the dash. Other parts in the pool have the dash, this one has no dash, should I add the dash to this part? I think all molex parts going forward should be one or the other.

**Comment by RX14** [comment]
The model in #185 has "License CC BY-ND 4.0" in it's header. That's incompatible with this repo, so I can't include that model.

**Pull request merged**
