### PR TITLE
Add STM32F103RxTx microcontroller

### PR DESCRIPTION
**Pull request by jue89**
Symbol, Unit, Entity: STM32F103RxTx
Part: STM32F103RCT6
Part: STM32F103RDT6
Part: STM32F103RET6

- Generated using https://github.com/horizon-eda/horizon/pull/522
- Deduplicated VDD and VSS pins
- Cleaned up pin names

### CODE REVIEW

**Comment by jue89** [comment]
Bot!

**Comment by carrotIndustries** [comment]
LGTM, but symbol should be expandable

**Comment by jue89** [comment]
Bot!

**Comment by RX14** [comment]
looks good to me

**Comment by jue89** [comment]
Thank you both for the very quick review :)

**Pull request merged**
