### PR TITLE
Add MXO-11 and MXO-11A 8.000MHz

### PR DESCRIPTION
**Pull request by RX14**
Datasheet here: https://docs.rs-online.com/6de8/0900766b816f8a84.pdf

### CODE REVIEW

**Comment by RX14** [comment]
A lot of oscillators seem to have a similar package so I'm a little iffy with saying it's manufacturer specific. It's a variation on DIP pin spacing but it doesn't seem to have a name...

**Comment by carrotIndustries** [comment]
This PR got selected as a test subject for the upcoming poolbot. Please find it's review below.

# Items in this PR
| State | Type | Name | Filename |
| --- | --- | --- | --- |
|New | Entity | MXO-11 | entities/oscillator/mita_denpa/MXO-11.json
|New | Package | MXO-11 | packages/manufacturer/mita_denpa/MXO-11/package.json
|New | Part | MXO-11 | parts/oscillator/mita_denpa/MXO-11.json
|New | Part | MXO-11A 8.0000MHz | parts/oscillator/mita_denpa/MXO-11A 8.0000MHz.json
|New | Symbol | MXO-11  (:warning: has trailing/leading whitespace) | symbols/oscillator/mita_denpa/MXO-11.json
|New | Unit | MXO-11  (:warning: has trailing/leading whitespace) | units/oscillator/mita_denpa/MXO-11.json

# Parts overview
Bold items are from this PR
- **Part MXO-11A 8.0000MHz**
  - **Part MXO-11**
    - **Entity MXO-11**
      - **Unit MXO-11 **
    - **Package MXO-11**
      - Padstack TH round
      - Padstack TH round with rectangular pad
# Details
## Parts
### MXO-11A 8.0000MHz
Inerhits from MXO-11
| Attribute | Value |
| --- | --- |
|MPN | MXO-11A 8.0000MHz
|Value | 8.0000MHz
|Manufacturer | MITA DENPA (2 other parts) (inherited)
|Datasheet | https://docs.rs-online.com/6de8/0900766b816f8a84.pdf (:warning: forbidden domain rs-online.com, use primary source) (inherited)
|Description | Crystal Oscillator (inherited)
|Tags | crystal oscillator
### MXO-11
| Attribute | Value |
| --- | --- |
|MPN | MXO-11
|Value | 
|Manufacturer | MITA DENPA (2 other parts)
|Datasheet | https://docs.rs-online.com/6de8/0900766b816f8a84.pdf (:warning: forbidden domain rs-online.com, use primary source)
|Description | Crystal Oscillator
|Tags | crystal oscillator
## Entities
### MXO-11
| Attribute | Value |
| --- | --- |
|Manufacturer | MITA DENPA (2 other parts)
|Prefix | U

| Gate | Suffix | Swap group | Unit |
| --- | --- | --- | --- |
|Main |  | 0 | MXO-11 
## Units
### MXO-11 
| Attribute | Value |
| --- | --- |
|Manufacturer | MITA DENPA (2 other parts)

| Pin | Direction | Alternate names |
| --- | --- | --- |
|5V | Power Input | 
|GND | Power Input | 
|OUT | Output |

**Comment by RX14** [comment]
Unfortunately I can't seem to source the datasheet from elsewhere

I'm not overly interested in this part any more, but I'm willing to fix up a few things to get it merged.

**Comment by carrotIndustries** [comment]
Bot!

**Comment by carrotIndustries** [comment]
- Assembly layer is missing pin 1 indication, also see checks.
 - Entity, etc can be made generic (Oscillator with single-ended output)

**Comment by RX14** [comment]
Is there an easy way to update pull requests from inside the pool manager? I can't work out how to add my changes to this PR

**Comment by RX14** [comment]
Pushed fixes for all the above

**Comment by carrotIndustries** [comment]
> Is there an easy way to update pull requests from inside the pool manager?

Unfortunately, no. I've yet been too afraid of all possible edge cases when updating PRs.

> Is a variation on DIP pin spacing but it doesn't seem to have a name...

I've had a look at KiCad's library and they just call it "Oscillator_DIP-14", so I think we can do something similar.

**Comment by RX14** [comment]
Bot!

**Comment by RX14** [comment]
Interesting the bot doesnt render the symbol refdes and value

**Comment by carrotIndustries** [comment]
> Interesting the bot doesn't render the symbol refdes and value, or the corner on the package assembly layer.

It does for me. Have you tried doing shift-reload to clear the cache?

2020-09-20-191720_479x581_scrot

**Comment by RX14** [comment]
> Have you tried doing shift-reload to clear the cache?

ah! I didnt realise it would be the same URL

**Comment by RX14** [comment]
Realised I forgot the courtyard program, perhaps add that as a check?

**Comment by carrotIndustries** [comment]
> Realised I forgot the courtyard program, would that work as a check?

Done in https://github.com/horizon-eda/horizon/commit/a414fba977055b4e79fd768d6b00ecd2bda90d17 and merged into the bot.

**Comment by RX14** [comment]
Nice! Is this ready to go?

**Comment by carrotIndustries** [comment]
Bot!

**Pull request merged**
