### PR TITLE
add FT232RL USB UART interface

### PR DESCRIPTION
**Pull request by jue89**
- part
- symbol
- TSSOP-28 package

### CODE REVIEW

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Bot!

**Comment by carrotIndustries** [comment]
LGTM, some minor nitpicks (also apply to the other PR)

 - Manufacturer name can be abbreviated to FTDI, that's how everyone I know calls them
 - Tray packaging isn't for SSOP package

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Thanks for reviewing!

**Comment by RX14** [comment]
Looks good to me

**Pull request merged**
