### PR TITLE
Add molex picoblade 4-pin connector

### PR DESCRIPTION
**Pull request by RX14**
Manufactured and test soldered (by hand) on a board of mine

### CODE REVIEW

**Comment by RX14** [comment]
Bot!

**Comment by carrotIndustries** [comment]
The mounting pads should be called M1/M2 and should have electrical connection in case someone wants to connect them to a ground plane for increased rigidity.

**Comment by RX14** [comment]
That's quite annoying since now it needs a different schematic symbol... But that seems sensible.

**Comment by RX14** [comment]
Bot!

**Comment by carrotIndustries** [comment]
Hm, I'd have used the generic 5 pin connector

**Comment by RX14** [comment]
well its not really a pin, and it's super confusing to select a 4 pin connector and get a 5 pin schematic symbol with no explanation.

Connecting these pads to a plane makes a lot of sense mechanically, but it's hella awkward in the schematic whatever you do.

**Pull request merged**
