### PR TITLE
Add Analog Devices AD7764 24Bit ADC

### PR DESCRIPTION
**Pull request by fk0815**
New part, including symbol, unit and entity.

AD7764 24-Bit, 312 kSPS, 109 dB Sigma-Delta ADC

### CODE REVIEW

**Comment by fk0815** [comment]
Bot!

**Comment by RX14** [comment]
> AD7764BRUZ

Usually this part would be added as `AD7764` with `AD7764BRUZ` as an orderable MPN.

Also, I'd usually recommend turning the text on the bottom and top pins to be horizontal, but there's just so many power pins here. What's others opinions here?

**Comment by carrotIndustries** [comment]
> Usually this part would be added as AD7764 with AD7764BRUZ as an orderable MPN.

If there's only one orderable MPN, I don't see a reason to do it that way. However, this part is available under 2 MPNs, so that's okay.

> but there's just so many power pins here. 

Yes, that'd make the symbol too large.

**Comment by carrotIndustries** [comment]
Looks good to me apart from the orderable MPNs as this part is available as AD7764BRUZ and AD7764BRUZ-REEL7

**Comment by fk0815** [comment]
Bot!

**Comment by fk0815** [comment]
I added the missing MPN, any more hints for this one?

**Comment by RX14** [comment]
Looks good to me pending @carrotIndustries finding time to re-review.

**Pull request merged**
