### PR TITLE
Add part 34AA02T-I/OT

### PR DESCRIPTION
**Pull request by fk0815**
Add 34AA02T-I/OT with generic I2C EEPROM symbol with 2 address lines

### CODE REVIEW

**Comment by fk0815** [comment]
Bot!

**Comment by fk0815** [comment]
Bot!

**Comment by fk0815** [comment]
Bot!

**Comment by RX14** [comment]
There's an unfortunate typo: "EERPOM"

**Comment by fk0815** [comment]
Bot!

**Review by RX14 — APPROVED** [review]

**Pull request merged**
