### PR TITLE
Add DMG6968UDM Dual N-Channel MOSFET

### PR DESCRIPTION
**Pull request by fk0815**
SOT-26 is an alias for SOT-23-6

### CODE REVIEW

**Comment by fk0815** [comment]
Bot!

**Comment by carrotIndustries** [comment]
This part isn't just two MOSFETs in one package, so that should be reflected in the entity.

**Comment by fk0815** [comment]
You mean the internally connected drain pins? How can the entity model a connection of the pins of two gates? Or should I add a new symbol with two connected mosfets?

**Comment by carrotIndustries** [comment]
> You mean the internally connected drain pins

That and the gate resistor and the diode. Add a new unit, symbol and entity for this part.

**Comment by fk0815** [comment]
Bot!

**Comment by carrotIndustries** [comment]
I think having one of the mosfets mirrored vertically is a bit confusing. Why not put them next to each other by mirroring one horizontally?

**Comment by fk0815** [comment]
Bot!

**Pull request merged**
