### PR TITLE
add BT134W-600W Triac

### PR DESCRIPTION
**Pull request by jue89**
This PR includes a Triac symbol. I've tried to align the look to the existing transistor symbol.

I've picked the reference designator "D".

Screenshot from 2020-12-15 13-08-57

### CODE REVIEW

**Comment by carrotIndustries** [comment]
Bot!

**Comment by jue89** [comment]
Hmm, big thumbs ... the commit message isn't correct. I'll fix this during review process.

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Now the "G" in the symbol is in the right place for all orientations. The commit message is fixed, as well.

**Comment by jue89** [comment]
Some minor adjustments - after stumbling over the [pool conventions' recommended prefixes](https://github.com/horizon-eda/horizon-pool-convention#prefixes-reference-designators):

* moved part, entity, unit and symbol from `diode` into `transistor` folder
* prefix is now `Q`

Futhermore, I added the orderable MPN so stock info is displayed.

**Comment by jue89** [comment]
Bot!

**Comment by fruchti** [comment]
I like the symbol! The data sheet link should point to the manufacturer (https://www.ween-semi.com/sites/default/files/2018-10/bt134w-600e.pdf) instead of Mouser, though.

I cross-checked the pinout and it matches the data sheet.

**Comment by jue89** [comment]
Bot!

**Comment by jue89** [comment]
Thank you for your review!

**Comment by carrotIndustries** [comment]
The symbol is is really nice indeed!

**Pull request merged**
